//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIWCeRegister.Source.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class m_occupation
    {
        public m_occupation()
        {
            this.members = new HashSet<member>();
        }
    
        public int Id { get; set; }
        public string Occupation_Name { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<member> members { get; set; }
    }
}
