//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Runtime.Serialization;
using ProtoBuf;

namespace PIWCeRegister.Source.Models
{
    using System;
    using System.Collections.Generic;

    [ProtoContract]
    [DataContract]
    public partial class m_occupation : IModel
    {
        public m_occupation()
        {
            this.members = new HashSet<member>();
        }
        [DataMember]
        public int Id { get; set; }
        [DataMember]
        public string Occupation_Name { get; set; }
        [DataMember]
        public string Description { get; set; }
        [DataMember]
        public virtual ICollection<member> members { get; set; }
    }
}
