//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIWCeRegister.Source.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class non_member
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Mobile_no { get; set; }
        public string Purpose { get; set; }
        public Nullable<int> Comment { get; set; }
    }
}
