//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Runtime.Serialization;
using ProtoBuf;

namespace PIWCeRegister.Source.Models
{
    using System;
    using System.Collections.Generic;

    [ProtoContract]
    [DataContract]
    public partial class ch_services : IModel<ch_services>
    {
        public ch_services()
        {
            this.members = new HashSet<member>();
        }

        [ProtoMember(1)]
        [DataMember]
        public int Id { get; set; }

        [ProtoMember(2)]
        [DataMember]
        public Nullable<int> Type { get; set; }

        [ProtoMember(3)]
        [DataMember]
        public Nullable<System.DateTime> Date { get; set; }

        [ProtoMember(4)]
        [DataMember]
        public virtual services_types services_types { get; set; }

        [ProtoMember(5,OverwriteList = true)]
        [DataMember]
        public virtual ICollection<member> members { get; set; }

        public bool Equals(ch_services other)
        {
            if (other == null) return false;

            return (
                (Type == other.Type)
                && (Date == other.Date))
                
            ;
        }
    }
}
