//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIWCeRegister.Source.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ch_services
    {
        public ch_services()
        {
            this.members = new HashSet<member>();
        }
    
        public int Id { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual services_types services_types { get; set; }
        public virtual ICollection<member> members { get; set; }
    }
}
