//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Runtime.Serialization;
using ProtoBuf;

namespace PIWCeRegister.Source.Models
{
    using System;
    using System.Collections.Generic;

    [ProtoContract]
    [DataContract]
    public partial class m_occupation : IModel<m_occupation>
    {
        public m_occupation()
        {
            this.members = new HashSet<member>();
        }

        [ProtoMember(1)]
        [DataMember]
        public int Id { get; set; }

        [ProtoMember(2)]
        [DataMember]
        public string Occupation_Name { get; set; }

        [ProtoMember(3)]
        [DataMember]
        public string Description { get; set; }

        
        public virtual ICollection<member> members { get; set; }

        public bool Equals(m_occupation other)
        {
            if (other == null) return false;

            return (Occupation_Name == other.Occupation_Name);
        }
    }
}
