//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIWCeRegister.Source.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class member
    {
        public member()
        {
            this.ch_services = new HashSet<ch_services>();
        }
    
        public int Id { get; set; }
        public string Pim_no { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Telephone_no { get; set; }
        public string Mobile_no { get; set; }
        public Nullable<int> Id_Address { get; set; }
        public Nullable<int> Id_Occupation { get; set; }
    
        public virtual address address { get; set; }
        public virtual m_occupation m_occupation { get; set; }
        public virtual ICollection<ch_services> ch_services { get; set; }
    }
}
