//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Runtime.Serialization;
using ProtoBuf;

namespace PIWCeRegister.Source.Models
{
    using System;
    using System.Collections.Generic;

    [ProtoContract]
    [DataContract]
    public partial class services_types : IModel<services_types>
    {
        public services_types()
        {
            this.ch_services = new HashSet<ch_services>();
        }

        [ProtoMember(1)]
        [DataMember]
        public int Id { get; set; }

        [ProtoMember(2)]
        [DataMember]
        public string Type_Name { get; set; }

        [ProtoMember(3)]
        [DataMember]
        public string Description { get; set; }

       
        public virtual ICollection<ch_services> ch_services { get; set; }

        public bool Equals(services_types other)
        {
            if (other == null) return false;

            return (
              (Type_Name == other.Type_Name)
          );
        }
    }
}
